### ISSUE TITLE
Bug duplicate refresh token 

### ISSUE THREAD

**Issue by davidzwa** [fdm-monster/fdm-monster#2413]
```
"Server experienced an internal error"
stack
: 
"MongoServerError: E11000 duplicate key error collection: fdm-monster.refreshtokens index: userId_1 dup key: { userId: ObjectId('65215cd6f0e6eb15d43ff5b2') }\n    at \\Projects\\fdm-monster\\node_modules\\mongodb\\lib\\operations\\insert.js:53:33\n    at \\fdm-monster\\node_modules\\mongodb\\lib\\cmap\\connection_pool.js:333:25\n    at \\fdm-monster\\node_modules\\mongodb\\lib\\sdam\\server.js:210:17\n    at handleOperationResult (\\fdm-monster\\node_modules\\mongodb\\lib\\sdam\\server.js:326:20)\n    at Connection.onMessage (\\fdm-monster\\node_modules\\mongodb\\lib\\cmap\\connection.js:243:9)\n    at MessageStream.<anonymous> (\\fdm-monster\\node_modules\\mongodb\\lib\\cmap\\connection.js:61:60)\n    at MessageStream.emit (node:events:514:28)\n    at MessageStream.emit (node:domain:489:12)\n    at processIncomingData (\\fdm-monster\\node_modules\\mongodb\\lib\\cmap\\message_stream.js:125:16)\n    at MessageStream._write (\\fdm-monster\\node_modules\\mongodb\\lib\\cmap\\message_stream.js:33:9)"
type
: 
"MongoServerError"
```

**Comment by davidzwa** [comment]
This was an index that was out-of-sync.
