### ISSUE TITLE
Firmware download endpoint 500 exception

### ISSUE THREAD

**Issue by davidzwa** [fdm-monster/fdm-monster#707]
- [x] I confirm that I'm a developer of FDM Monster and allowed to use this template.

- **Description**
Firmware internal download causes 500 on first download

{"error":"Server experienced an internal error","type":"TypeError","stack":"TypeError: The \"chunk\" argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of Array\n    at new NodeError (node:internal/errors:372:5)\n    at _write (node:internal/streams/writable:312:13)\n    at WriteStream.Writable.write (node:internal/streams/writable:334:10)\n    at write (C:\\Users\\david\\Documents\\Projects\\fdm-monster\\server\\services\\multer.service.js:46:18)\n    at new Promise (<anonymous>)\n    at MulterService.downloadFile (C:\\Users\\david\\Documents\\Projects\\fdm-monster\\server\\services\\multer.service.js:45:18)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at PluginFirmwareUpdateService.downloadFirmware (C:\\Users\\david\\Documents\\Projects\\fdm-monster\\server\\services\\octoprint\\plugin-firmware-update.service.js:84:7)\n    at PluginFirmwareUpdateController.downloadFirmware (C:\\Users\\david\\Documents\\Projects\\fdm-monster\\server\\controllers\\plugin-firmware-update.controller.js:45:5)"}

**Comment by davidzwa** [comment]
This was in test only and made perfect sense. Closing as this is not something I will fix soon.
